ANIMAL_AVATARS = [
    ("🦁", "Lion Leader",   "Bold & Commanding"),
    ("🦊", "Clever Fox",    "Sharp & Strategic"),
    ("🐼", "Calm Panda",    "Cool Under Pressure"),
    ("🐨", "Team Koala",    "Collaborative & Kind"),
    ("🦥", "Steady Sloth",  "Thoughtful & Deep"),
    ("🦄", "Unicorn",       "Creative & Inspiring"),
]

FOCUS_OPTIONS = [
    ("Interview Prep", "🎤"),
    ("Public Speaking", "🎙️"),
    ("Leadership Pitching", "💼"),
    ("Active Listening", "👂"),
]

LEVELS = [
    {
        "id": 1,
        "title": "First Impressions",
        "icon": "👋",
        "difficulty": "Beginner",
        "xp": 50,
        "color": "#58cc02",
        "shadow": "#46a302",
        "scenario": "You've just walked into a networking event. Introduce yourself to a stranger memorably.",
        "questions": [
            {
                "q": "Introduce yourself to a new colleague at a networking event!",
                "hint": "Include your name, role, and one interesting hook.",
                "keywords": ["name", "work", "passionate", "excited", "love", "help", "focus", "specialize", "great", "pleasure"],
                "forbidden": ["um", "uh", "like", "basically", "literally", "you know", "i guess", "sort of", "kind of"],
            },
            {
                "q": "Someone asks: 'So, what do you do?' — give your best 30-second answer.",
                "hint": "Avoid job-title-only answers. Tell a mini-story about impact.",
                "keywords": ["impact", "help", "team", "result", "build", "create", "improve", "lead", "drive", "achieve"],
                "forbidden": ["um", "uh", "like", "basically", "literally", "just", "sort of"],
            },
            {
                "q": "A senior executive just sat next to you. Start a meaningful conversation.",
                "hint": "Lead with curiosity, not self-promotion.",
                "keywords": ["curious", "interesting", "question", "perspective", "insight", "opportunity", "challenge", "vision"],
                "forbidden": ["um", "uh", "like", "basically", "nervous", "sorry", "i don't know"],
            },
        ],
        "rubric_items": [
            "Clear and confident self-introduction",
            "Memorable hook or unique angle",
            "Showed genuine interest in the other person",
            "Maintained upbeat, friendly tone",
            "Natural, not rehearsed-sounding",
        ],
    },
    {
        "id": 2,
        "title": "Active Listening",
        "icon": "👂",
        "difficulty": "Beginner",
        "xp": 75,
        "color": "#58cc02",
        "shadow": "#46a302",
        "scenario": "Your team member comes to you frustrated about a project. Listen and respond with empathy.",
        "questions": [
            {
                "q": "A colleague says: 'I feel like my ideas are never taken seriously.' Respond with empathy.",
                "hint": "Acknowledge their feeling before offering solutions.",
                "keywords": ["hear", "understand", "feel", "valid", "appreciate", "share", "tell", "experience", "perspective", "must"],
                "forbidden": ["but", "however", "actually", "wrong", "no", "um", "uh"],
            },
            {
                "q": "Summarize back what you heard to confirm understanding.",
                "hint": "Use 'What I'm hearing is...' or 'It sounds like...' framing.",
                "keywords": ["hearing", "sounds", "sense", "understand", "confirm", "right", "correct", "mean", "feeling", "situation"],
                "forbidden": ["um", "uh", "basically", "whatever", "anyway"],
            },
            {
                "q": "Someone just shared exciting news about their promotion. Respond as an active listener.",
                "hint": "Match their energy. Ask questions that show you care.",
                "keywords": ["congratulations", "amazing", "wonderful", "tell", "feel", "exciting", "proud", "celebrate", "deserve", "journey"],
                "forbidden": ["um", "uh", "oh", "cool", "nice", "ok", "whatever"],
            },
        ],
        "rubric_items": [
            "Validated the speaker's feelings first",
            "Accurately paraphrased or summarized",
            "Asked a thoughtful clarifying question",
            "Avoided jumping to solutions prematurely",
            "Warm and non-judgmental tone throughout",
        ],
    },
    {
        "id": 3,
        "title": "Storytelling",
        "icon": "📖",
        "difficulty": "Beginner",
        "xp": 100,
        "color": "#58cc02",
        "shadow": "#46a302",
        "scenario": "Great communicators tell stories, not facts. Structure your experiences as compelling narratives.",
        "questions": [
            {
                "q": "Tell a challenge you overcame at work using the STAR format.",
                "hint": "Situation → Task → Action → Result. End with a number.",
                "keywords": ["situation", "challenge", "task", "action", "result", "increased", "improved", "achieved", "reduced", "led"],
                "forbidden": ["um", "uh", "like", "basically", "i think", "maybe", "kind of"],
            },
            {
                "q": "Describe a time you convinced someone who disagreed with you.",
                "hint": "Focus on HOW you persuaded, not just that you did.",
                "keywords": ["listen", "understand", "perspective", "evidence", "data", "agree", "solution", "compromise", "together", "outcome"],
                "forbidden": ["um", "uh", "forced", "made them", "had to", "whatever"],
            },
            {
                "q": "Tell a 60-second story that illustrates your biggest professional strength.",
                "hint": "Show, don't tell. A story beats a claim every time.",
                "keywords": ["strength", "example", "specifically", "result", "team", "impact", "proud", "learned", "grew", "transformed"],
                "forbidden": ["um", "uh", "like", "basically", "i'm good at", "i think i'm"],
            },
        ],
        "rubric_items": [
            "Clear situation/context established",
            "Specific actions described (not vague)",
            "Quantified or concrete result mentioned",
            "Emotional engagement or narrative tension",
            "Appropriate pacing and length",
        ],
    },
    {
        "id": 4,
        "title": "Elevator Pitch",
        "icon": "🚀",
        "difficulty": "Intermediate",
        "xp": 125,
        "color": "#1cb0f6",
        "shadow": "#1899d6",
        "scenario": "You're in an elevator with a key decision-maker. 60 seconds. Make it count.",
        "questions": [
            {
                "q": "Pitch your project to a skeptical CEO in 60 seconds.",
                "hint": "Problem → Solution → Impact → Ask. No jargon.",
                "keywords": ["problem", "solution", "impact", "revenue", "save", "increase", "customers", "market", "invest", "opportunity"],
                "forbidden": ["um", "uh", "like", "basically", "synergy", "leverage", "paradigm"],
            },
            {
                "q": "'Why should I fund you over 10 other candidates?' Respond.",
                "hint": "Lead with your unique differentiator, then evidence.",
                "keywords": ["unique", "proven", "track record", "results", "data", "experience", "differentiate", "specifically", "delivered", "measurable"],
                "forbidden": ["um", "uh", "i think", "maybe", "hopefully", "possibly", "i guess"],
            },
            {
                "q": "30 seconds to pitch yourself for a role you really want. Go.",
                "hint": "Who you are + what you do best + why them.",
                "keywords": ["passion", "expertise", "results", "align", "mission", "contribute", "specifically", "value", "bring", "achieve"],
                "forbidden": ["um", "uh", "like", "basically", "i'm just", "i don't know", "sort of"],
            },
        ],
        "rubric_items": [
            "Clear problem statement in opening",
            "Specific, jargon-free solution",
            "Quantified or concrete business impact",
            "Confident and energetic tone",
            "Strong call-to-action at end",
        ],
    },
    {
        "id": 5,
        "title": "Conflict Resolution",
        "icon": "🤝",
        "difficulty": "Intermediate",
        "xp": 150,
        "color": "#1cb0f6",
        "shadow": "#1899d6",
        "scenario": "Workplace conflicts are inevitable. Navigate them with grace and assertiveness.",
        "questions": [
            {
                "q": "A colleague dismissed your idea publicly. How do you address it privately?",
                "hint": "Stay factual, not emotional. Use 'I' statements.",
                "keywords": ["i felt", "i noticed", "impact", "understand", "perspective", "resolve", "together", "move forward", "appreciate", "discuss"],
                "forbidden": ["you always", "you never", "your fault", "stupid", "wrong", "um", "uh"],
            },
            {
                "q": "Two team members are in conflict. As team lead, how do you mediate?",
                "hint": "Listen to both. Focus on shared goals.",
                "keywords": ["both", "each", "shared", "goal", "understand", "neutral", "together", "solution", "forward", "support"],
                "forbidden": ["wrong", "blame", "fault", "um", "uh", "whoever", "just stop"],
            },
            {
                "q": "A client is angry about a missed deadline. Walk through your response.",
                "hint": "Acknowledge → Apologize → Action plan. No excuses first.",
                "keywords": ["apologize", "understand", "impact", "action", "plan", "committed", "priority", "immediate", "ensure", "prevent"],
                "forbidden": ["but", "because", "excuse", "um", "uh", "wasn't my", "not my fault"],
            },
        ],
        "rubric_items": [
            "Used I-statements (not blame language)",
            "Acknowledged the other person's perspective",
            "Stayed calm and professional in tone",
            "Offered a concrete resolution or next step",
            "Preserved the relationship",
        ],
    },
    {
        "id": 6,
        "title": "Leadership Voice",
        "icon": "🎙️",
        "difficulty": "Advanced",
        "xp": 175,
        "color": "#a346ff",
        "shadow": "#8238cc",
        "scenario": "Leaders inspire action through words. Practice authority, clarity, and authenticity.",
        "questions": [
            {
                "q": "Your team just hit a major setback. Rally them in 60 seconds.",
                "hint": "Acknowledge the difficulty. Paint a clear path forward. Believe in them.",
                "keywords": ["together", "believe", "strength", "path", "overcome", "resilient", "committed", "forward", "trust", "achieve"],
                "forbidden": ["um", "uh", "disaster", "terrible", "hopeless", "i don't know", "maybe"],
            },
            {
                "q": "Deliver critical feedback to a high-performer becoming arrogant.",
                "hint": "Lead with appreciation, then address behavior, not the person.",
                "keywords": ["value", "contribution", "impact", "behavior", "specifically", "team", "together", "expect", "support", "growth"],
                "forbidden": ["arrogant", "attitude", "problem", "always", "never", "um", "uh"],
            },
            {
                "q": "Announce an unpopular decision to your team. How do you communicate it?",
                "hint": "Explain the why. Acknowledge impact. Open for questions.",
                "keywords": ["reason", "because", "understand", "impact", "together", "support", "questions", "open", "decision", "move forward"],
                "forbidden": ["um", "uh", "just deal", "no choice", "have to", "tough luck"],
            },
        ],
        "rubric_items": [
            "Spoke with authority and confidence",
            "Showed genuine empathy for their audience",
            "Gave a clear direction or decision",
            "Inspired rather than just informed",
            "Invited dialogue or questions",
        ],
    },
    {
        "id": 7,
        "title": "Data Storytelling",
        "icon": "📊",
        "difficulty": "Advanced",
        "xp": 200,
        "color": "#a346ff",
        "shadow": "#8238cc",
        "scenario": "Numbers don't speak for themselves. Turn data into a compelling narrative.",
        "questions": [
            {
                "q": "Customer churn increased 18% last quarter. Present this to the board.",
                "hint": "Context → Insight → Implication → Recommendation.",
                "keywords": ["context", "insight", "because", "therefore", "recommend", "action", "impact", "revenue", "customers", "address"],
                "forbidden": ["um", "uh", "basically", "i think", "maybe", "not sure", "kind of"],
            },
            {
                "q": "Explain a complex technical process to a non-technical executive in 60s.",
                "hint": "Use an analogy. Avoid acronyms. Focus on business value.",
                "keywords": ["imagine", "like", "similar", "means", "value", "business", "result", "enables", "allows", "simply"],
                "forbidden": ["um", "uh", "api", "backend", "frontend", "algorithm", "basically", "technical"],
            },
            {
                "q": "Your results are mixed — wins and misses. Present honestly without sounding defensive.",
                "hint": "Lead with honesty. Own misses. Double down on learnings.",
                "keywords": ["proud", "learned", "improve", "next", "action", "honest", "achieved", "missed", "because", "plan"],
                "forbidden": ["um", "uh", "blame", "their fault", "wasn't me", "not fair", "anyway"],
            },
        ],
        "rubric_items": [
            "Led with the key insight, not raw data",
            "Connected data to business impact",
            "Used plain language (no jargon)",
            "Gave a clear recommendation",
            "Structured logically (context → insight → action)",
        ],
    },
    {
        "id": 8,
        "title": "Boardroom Master",
        "icon": "👑",
        "difficulty": "Expert",
        "xp": 250,
        "color": "#ffd700",
        "shadow": "#e8b400",
        "scenario": "The ultimate test. You're in the boardroom. Combine everything you've learned.",
        "questions": [
            {
                "q": "Present a full business proposal in 90s: problem, solution, investment, ROI.",
                "hint": "Hook → Problem → Solution → Numbers → Ask.",
                "keywords": ["problem", "solution", "invest", "return", "roi", "market", "revenue", "achieve", "strategy", "opportunity"],
                "forbidden": ["um", "uh", "like", "basically", "i think maybe", "not sure", "guess"],
            },
            {
                "q": "'This is too risky.' Handle this board objection.",
                "hint": "Acknowledge. Reframe risk. Provide evidence.",
                "keywords": ["understand", "mitigate", "evidence", "data", "risk", "managed", "proven", "similar", "return", "confident"],
                "forbidden": ["um", "uh", "risky", "scared", "worried", "i don't know", "hopefully"],
            },
            {
                "q": "Close the meeting by summarizing decisions and next steps.",
                "hint": "Recap decisions. Assign owners. Set timeline. Thank contributors.",
                "keywords": ["agreed", "decided", "responsible", "deadline", "next", "thank", "appreciate", "aligned", "committed", "clear"],
                "forbidden": ["um", "uh", "i think", "maybe", "not sure", "whatever", "anyway"],
            },
        ],
        "rubric_items": [
            "Opened with a compelling hook",
            "All key business components covered",
            "Handled pressure or complexity with grace",
            "Used numbers or evidence effectively",
            "Closed with clear next steps and alignment",
        ],
    },
]

LEVELS_BY_ID = {l["id"]: l for l in LEVELS}
